language: ruby
sudo: required
dist: xenial
before_install:
 - sudo apt-get update
 - sudo apt-get install python3 python3-dev python3-pip python3-yaml -y
script:
  - bundle install
  - bundle exec jekyll build --drafts
  - python2 --version && python2 -m pip --version
  - python2 -m pip install html5validator --user --upgrade
  - ~/.local/bin/html5validator --root _site/
  - python3 -m pip install git+https://github.com/DanielOaks/yamltypes.git@ircv3-fixes#egg=yamltypes --user --upgrade
  - ~/.local/bin/yamlvalidate $(find _data | grep \.yml | xargs) --path _data/validation
rvm: 2.6.2
notifications:
    email: false
matrix:
    fast_finish: true
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
