name: IRCv3 Working Group
markdown: kramdown
highlighter: rouge
# baseurl: http://ircv3.net
liveurl: http://ircv3.net  # used in XML feeds
repository: ircv3/ircv3.github.io
kramdown:
  input: GFM
  auto_ids: false
exclude:
  - README.md
  - vendor
  - Gemfile*
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
sass:
    sass_dir: css
sitemap:
  file: "/sitemap.xml"
collections:
  irc:
    output: true
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  blanklines: true
